# Site settings
title: Profound Guild
realm: Jaedenar
baseurl: ""
url: "http://profoundguild.github.io"
permalink: /:year/:month/:title
paginate: 5
paginate_path: "/page/:num"

# Build settings
markdown: kramdown