# Site settings
title: Profound Guild
realm: Jaedenar
baseurl: ""
url: "http://profoundguild.github.io"
permalink: /:year/:month/:title
paginate: 5
paginate_path: "/page/:num"
timezone: Europe/London

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"